---
title: The Noon Room
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
    description: My thoughts and ideas
    feature_text: 'Welcome to the blog

'
    feature_image: https://unsplash.it/1300/400?image=1067
  tools:
    title: Tools
    output: true
    permalink: "/tool/:name"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    image: "/assets/placeholder-social.png"
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: "/assets/placeholder-social.png"
exclude:
- README.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji
paginate: 2
paginate_path: blog/page:num
jekyll-mentions: https://twitter.com
twitter: 
username: noonpacific
author: Noon Pacific
social:
  name: Noon Pacific
  links:
  - https://twitter.com/noonpacific
  - https://www.facebook.com/noonpacific
  - https://instagram.com/noonpacific
sass:
  style: compressed
permalink: pretty
excerpt_separator: "<!-- more -->"
encoding: utf-8
logo: "/assets/placeholder-logo.svg"
description: A curated directory of tools for musicians, by Noon Pacific
url: https://room.noonpacific.com
repo: https://github.com/cdinnison/noon-room
email: hello@noonpacific.com
avatarurl: "#"
navigation_header:
  Home: "/"
  About: "/about/"
navigation_footer:
  Created by Noon Pacific: https://noonpacific.com
social_links:
  Twitter: https://twitter.com/noonpacific
  GitHub: https://github.com/noonpacific
  link: https://noonpacific.com
sharing_links:
  Twitter: "#1DA1F2"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  Pinterest: "#BD081C"
  LinkedIn: "#0077B5"
  tumblr: "#36465D"
  Reddit: "#FF4500"
  Hacker News: "#ff6600"
  Designer News: "#2D72D9"
