---
title: Noon Room
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
    description: My thoughts and ideas
    feature_text: 'Welcome to the blog

'
    feature_image: https://unsplash.it/1300/400?image=1067
  tools:
    title: Tools
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    image: "/assets/placeholder-social.png"
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: "/assets/placeholder-social.png"
exclude:
- README.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji
paginate: 2
paginate_path: blog/page:num
jekyll-mentions: https://twitter.com
twitter:
username: noonpacific # jekyll-seo-tag > Owners twitter username
author: Noon Pacific # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Noon Pacific # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/noonpacific
    - https://www.facebook.com/noonpacific
    - https://instagram.com/noonpacific

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://unsplash.it/1300/400?image=1067"
  tools:
    title: Tools
    output: true
    permalink: /tool/:name

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "The Noon Room" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/placeholder-logo.svg" # Site logo, also used in jekyll-seo-tag
description: "A curated directory of tools for musicians, by Noon Pacific" # Site description and default description, also used in jekyll-seo-tag
url: "https://room.noonpacific.com" # Site url, also used in jekyll-seo-tag
repo: "https://github.com/cdinnison/noon-room"
email: "hello@noonpacific.com"
avatarurl: "#" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Home: /
  About: /about/

navigation_footer:
  Created by Noon Pacific: https://noonpacific.com

social_links:
  Twitter: https://twitter.com/noonpacific
  GitHub: https://github.com/noonpacific
  link: https://noonpacific.com

sharing_links:
  Twitter: "#1DA1F2"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  Pinterest: "#BD081C"
  LinkedIn: "#0077B5"
  tumblr: "#36465D"
  Reddit: "#FF4500"
  Hacker News: "#ff6600"
  Designer News: "#2D72D9"
