---
title: Alembic
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
    description: My thoughts and ideas
    feature_text: 'Welcome to the blog

'
    feature_image: https://unsplash.it/1300/400?image=1067
  tools:
    title: Tools
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    image: "/assets/placeholder-social.png"
- scope:
    path: ''
    type: posts
  values:
    layout: post
    image: "/assets/placeholder-social.png"
exclude:
- README.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- demo/*
- alembic-jekyll-theme.gemspec
gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji
paginate: 2
paginate_path: blog/page:num
jekyll-mentions: https://twitter.com
twitter:
  username: DavidDarnes
author: DavidDarnes
social:
  name: David Darnes
  links:
  - https://twitter.com/DavidDarnes
  - https://www.facebook.com/daviddarnes
  - https://www.linkedin.com/in/daviddarnes
  - https://plus.google.com/+DavidDarnes
  - https://github.com/daviddarnes
sass:
  style: compressed
permalink: pretty
excerpt_separator: "<!-- more -->"
encoding: utf-8
logo: "/assets/placeholder-logo.svg"
description: Alembic is a starting point for Jekyll projects. Rather than starting
  from scratch, this boilerplate is designed to get the ball rolling immediately
url: https://alembic.darn.es
repo: https://github.com/daviddarnes/alembic
email: me@daviddarnes.com
disqus: alembic-1
avatarurl: https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c
navigation_header:
  Home: "/"
  Elements: "/elements/"
  Blog: "/blog/"
  Categories: "/categories/"
  Search: "/search/"
  Fork Alembic: https://github.com/daviddarnes/alembic
navigation_footer:
  Created by David Darnes: https://darn.es
social_links:
  Twitter: https://twitter.com/DavidDarnes
  LinkedIn: https://www.linkedin.com/in/daviddarnes
  Google+: https://plus.google.com/+DavidDarnes
  GitHub: https://github.com/daviddarnes
  link: https://darn.es
sharing_links:
  Twitter: "#1DA1F2"
  facebook: "#3B5998"
  Google+: "#DC4E41"
  Pinterest: "#BD081C"
  LinkedIn: "#0077B5"
  tumblr: "#36465D"
  Reddit: "#FF4500"
  Hacker News: "#ff6600"
  Designer News: "#2D72D9"
  Email: ''
